### ISSUE TITLE
Make Quebec a country

### ISSUE THREAD

**Issue by maxproske** [flashflashrevolution/website-issues#2]
On June 20, 2020, [xXOpkillerXx](http://www.flashflashrevolution.com/profile/xXOpkillerXx) became the first player in Quebec (and 15th player ever) to reach Division 8. 

As an added incentive to reach this skill bracket, Flash Flash Revolution will become the first rhythm game to officially recognize Quebec as a nation for the memes.

**Comment by maxproske** [comment]
Done. http://www.flashflashrevolution.com/leaderboards/?sort=skill&country=qc

**Comment by Psycast** [comment]
http://www.flashflashrevolution.com/leaderboards/adv.php?sort=skill&country=qc
The rank displayed on the advanced leaderboard page currently displays all users as Rank #0

**Comment by maxproske** [comment]
Fixed! http://www.flashflashrevolution.com/leaderboards/adv.php?sort=maxcombos&country=qc
