### ISSUE TITLE
Requesting a revised downloads section on the sidebar

### ISSUE THREAD

**Issue by Hakulyte** [flashflashrevolution/website-issues#3]
**Describe the issue**
FFR's Standalone Engine (rCubed) has multiple versions that can be found in various places. 
All this information should be easy to find and access. 

The benefit of having quick access to multiple versions  is that players can rapidly compare them to figure out which version works best for themselves.

**The current known options**
1. FFR's Download Button currently fetch the 0.0.8 version on the front page's sidebar.
![image](https://i.imgur.com/CkHi3Q7.png)

2. The forums under General Talk has a thread about the 1.0.1 OT Edition version.
Link: http://www.flashflashrevolution.com/vbz/showthread.php?t=151143
![image](https://i.imgur.com/GtoMQpx.png) 

3. FFR's Discord has a pinned message under the chit chat tab with the 0.0.8 version of the game.
![image](https://i.imgur.com/4RFJ96I.png)

4. FFR's github has a link to the more updated versions of FFR like 1.2.2 and 1.3.0 alpha
Link: https://github.com/flashflashrevolution/rCubed/releases
![image](https://i.imgur.com/TO4FBbx.png)

**Recommendations**
We shouldn't expect players to figure out that they need to visit the forums, discord or github.

The front page's sidebar seems like the best strategic place where players should have direct links to download. 

Something like this comes in mind:
![image](https://i.imgur.com/XEMhn4O.png)

Note that it could be interesting to also have a page with detailed information of what's different between versions like in 1.0.1's case on forums and the more recent updates on github.

This is why it may be interesting to redirect toward other links rather than directly have a download link. Maybe both links could be together as well for convenience.

I also think the FFR button could be recycled as a small banner to catch attention, but this is simply a personal preference,

**Comment by maxproske** [comment]
I see you :eyes:

I have a ready-made downloads page for the dev site, so I'll look into integrating it into the live site.

**Comment by Psycast** [comment]
Download page now contains a link to all previous versions of the game plus special version.
https://www.flashflashrevolution.com/download/versions.php
