### ISSUE TITLE
Division 8 forums badge

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/website-issues#4]
Just like the Division 7 got a badge on the forums (D7 Elite Keysmasher) when it was introduced, Division 8 needs a badge for consistency reasons.

Suggestions for the badge name:

- D8 Supreme Keysmasher
- D8 High-Elite Keysmasher
- D8 Ultimate Keysmasher

We have to keep in mind that with the recent-ish influx of top tier players (level 103+) and the upcoming OT (Official Tournament), it is very likely that even Division 8 will eventually represent a range that is too big to be coherent with the other divisions. That being said, titles like "Master Keysmasher" "Top Tier Keysmasher" for D8 could be problematic when/if we introduce D9 at some point.

For the image, here's a very quick attempt at one, but if might need to be polished a bit:
![ffr_godly](https://user-images.githubusercontent.com/20545324/85436605-515c3100-b557-11ea-9625-64b96471a552.png)

**Comment by maxproske** [comment]
Thank you, a quick recolour is great for now. I'll get this added soon.

**Comment by maxproske** [comment]
Added

![screenshot](https://i.imgur.com/9CHQDF4.png)
