### ISSUE TITLE
Tournament dashboard refresh loses tab selection

### ISSUE THREAD

**Issue by mat100payette** [flashflashrevolution/website-issues#7]
It would be very convenient if the tournament dashboard could keep the current selected tab on page refresh. That way, if a user is monitoring a specific division's scores, they don't have to always reselect that division's tab after refreshing the page.

**Comment by Zageron** [comment]
@flashflashrevolution/primary-contributors anyone want to take this on as a QOL improvement?

**Comment by G-flat** [comment]
@Zageron I could give this a shot, I guess?

**Comment by G-flat** [comment]
With help from @Psycast, the tournament dashboard now saves tab selection. Should this issue be closed?

**Comment by Zageron** [comment]
Yup all fixed!
http://www.flashflashrevolution.com/tournament/
