### ISSUE TITLE
Conflict in batch related information via Song Submission tab

### ISSUE THREAD

**Issue by ghost** [flashflashrevolution/website-issues#9]
This is specifically regarding information accessed through the "Song Submission" tab. With the new batch page linked via the "[Submit a Song](http://www.flashflashrevolution.com/batch_submission/batch/)" dropdown selection, the information via the "[Batch Search Engine](https://dossar.me/bse/)" selection contains some conflicts due to being outdated. 

Regarding the Batch Search Engine Home page, I'm assuming this is outdated because of anticipation for the new batch system put in place recently. However, there is still some viable information through this source that could be left accessible.

The primary issue I'm seeing is that users are given conflicting information on the current queue and judges between these two pages. My suggestion would be to remove this information within the Batch Search Engine area but keep anything historical. As an aside, I think that current judges should be referenced within the new batch page either directly or via a link to the [FFR team](http://www.flashflashrevolution.com/team/) page where the judges are already listed.

**Comment by Psycast** [comment]
Batch Search Engine has been retired for quite a while as functionality of the sites batch system has expanded.
